export const experienceItems = [
  {
    image: "/images/experience/example-1.webp",
    title: "Indicium AI",
    text: "A unified global brand for a pure-play AI consultancy.",
    labels: ["Brand", "Technology & AI"],
    bookTitle: "Book a call",
    bookText: "Let’s discuss your needs",
  },
  {
    image: "/images/experience/example-2.webp",
    title: "Indicium AI",
    text: "A unified global brand for a pure-play AI consultancy.",
    labels: ["Brand", "Technology & AI"],
    bookTitle: "Book a call",
    bookText: "Let’s discuss your needs",
  },
  {
    image: "/images/experience/example-3.webp",
    title: "Indicium AI",
    text: "A unified global brand for a pure-play AI consultancy.",
    labels: ["Brand", "Technology & AI"],
    bookTitle: "Book a call",
    bookText: "Let’s discuss your needs",
  },
  {
    image: "/images/experience/example-4.webp",
    title: "Indicium AI",
    text: "A unified global brand for a pure-play AI consultancy.",
    labels: ["Brand", "Technology & AI"],
    bookTitle: "Book a call",
    bookText: "Let’s discuss your needs",
  },
  {
    image: "/images/experience/example-5.webp",
    title: "Indicium AI",
    text: "A unified global brand for a pure-play AI consultancy.",
    labels: ["Brand", "Technology & AI"],
    bookTitle: "Book a call",
    bookText: "Let’s discuss your needs",
  },
];
